# Streaming Video Subscriptions

Subscription records for MavenFlix, a fictitious video streaming platform. Dataset includes information for ~2,900 subscribers from September 2022 through September 2023. Each record represents an individual customer's subscription, including the subscription cost, created/canceled date, interval, and payment status.

**Recommended Analysis**
* How have Mavenflix subscriptions trended over time? 
* What percentage of customers have subscribed for 5 months or more? 
* What month has the highest subscriber retention, the lowest retention?

Import Packages and Dataset, as well as Instantiate Constant Variables

In [ ]:
# Import Packages --------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme(style="darkgrid")

# Instantiate Constant Variables --------------
dataset_filename = "Subscription Cohort Analysis Data.csv";
dataset_dictionary_filename = "Subscription Cohort Analysis Data Dictionary.csv";

# Import Dataset ---------------------
df = pd.read_csv(dataset_filename);
df_dict = pd.read_csv(dataset_dictionary_filename);

In [8]:
print(df_dict.info());
df_dict.head()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Field        6 non-null      str
 1   Description  6 non-null      str
dtypes: str(2)
memory usage: 228.0 bytes
None

                   Field                                        Description
0            customer_id  Unique customer identification number represen...
1           created_date  Date the customer subscription was created (MM...
2          canceled_date  Date the customer subscription was canceled (M...
3      subscription_cost                   Price of the subscription in USD
4  subscription_interval  Measurement of time between billing occurrence...

In [9]:
print(df.info())
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 3069 entries, 0 to 3068
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   customer_id            3069 non-null   int64
 1   created_date           3069 non-null   str
 2   canceled_date          2004 non-null   str
 3   subscription_cost      3069 non-null   int64
 4   subscription_interval  3069 non-null   str
 5   was_subscription_paid  3069 non-null   str
dtypes: int64(2), str(4)
memory usage: 144.0 KB
None

,customer_id,created_date,canceled_date,subscription_cost,subscription_interval,was_subscription_paid
0,154536156,2022-09-01,NaN,39,month,Yes
1,149713408,2022-09-01,2022-09-02,39,month,No
2,153756284,2022-09-01,2022-09-02,39,month,No
3,121253113,2022-09-01,2022-09-23,39,month,Yes
4,154467210,2022-09-01,2023-06-29,39,month,Yes

**1. How have Mavenflix subscriptions trended over time?**

In [52]:
def trendOfSubscriptionsOverTime(data):
    dff = data.copy();
    dff['created_date'] = pd.to_datetime(dff['created_date']);
    dff = dff.sort_values(by=['created_date'], ascending=True);
    dff_agg = dff['created_date'].value_counts().sort_values();
    dataframe = pd.DataFrame({
        'Created Date': dff_agg.index.tolist(),
        'Count': dff_agg.values.tolist()
    });
    dataframe = dataframe.sort_values(by=['Created Date'], ascending=True).reset_index().drop(columns=['index']);
    dataframe['Created Date'] = pd.to_datetime(dataframe['Created Date']);
    # monthly_df = dff.groupby(dff['created_date'].dt.to_period('M')).sum(numeric_only=True);
    return dataframe;

trendOfSubscriptionsOverTime(df)

    Created Date  Count
0     2022-09-01     12
1     2022-09-02      6
2     2022-09-03     10
3     2022-09-04      9
4     2022-09-05     18
..           ...    ...
365   2023-09-04     15
366   2023-09-05     13
367   2023-09-06      8
368   2023-09-07      7
369   2023-09-08      3

[370 rows x 2 columns]